name: Hexlet CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

        # make depends on uv
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Run linter and pytest
        run: |
          uv run ruff check hexlet_code

      - name: Run test coverage
        run: |
          uv run pytest --cov=hexlet_code --cov-report=xml --cov-report=term-missing

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=hexlet-gendiff-project
            -Dsonar.organization=grekys84
            -Dsonar.sources=hexlet_code/
            -Dsonar.tests=hexlet_code/tests
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.version=3.14
            -Dsonar.exclusions=hexlet_code/tests/**,**/__pycache__/**,**/*.pyc
